apiVersion: v1
kind: Service
metadata:
  name: identity
  labels:
    name: identity
spec:
  type: LoadBalancer
  selector:
    name: identity
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
