apiVersion: v1
kind: Service
metadata:
  name: default
  labels:
    name: default
spec:
  type: LoadBalancer
  selector:
    name: default
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
